---

common_packages:
  - "net-tools"
  - "vnstat"
  - "curl"
  - "wget"
  - "socat"


# Timezone for server
common_timezone: "Europe/Moscow"

# Timeout for rebooting
common_reboot_timeout: 300

# System limit user
common_system_domain: "*"

# System limits
common_limits:
  - { domain: "{{ common_system_domain }}", type: '-', limit_item: 'core', value: "unlimited" }
  - { domain: "{{ common_system_domain }}", type: '-', limit_item: 'data', value: "unlimited" }
  - { domain: "{{ common_system_domain }}", type: '-', limit_item: 'fsize', value: "unlimited" }
  - { domain: "{{ common_system_domain }}", type: '-', limit_item: 'nofile', value: "1048576" }
  - { domain: "{{ common_system_domain }}", type: '-', limit_item: 'memlock', value: "unlimited" }
  - { domain: "{{ common_system_domain }}", type: '-', limit_item: 'rss', value: "unlimited" }
  - { domain: "{{ common_system_domain }}", type: '-', limit_item: 'nproc', value: "unlimited" }
  - { domain: "{{ common_system_domain }}", type: '-', limit_item: 'msgqueue', value: "unlimited" }
  - { domain: "{{ common_system_domain }}", type: 'hard', limit_item: 'stack', value: "65536" }
  - { domain: "{{ common_system_domain }}", type: 'soft', limit_item: 'stack', value: "32768" }
  - { domain: "{{ common_system_domain }}", type: '-', limit_item: 'cpu', value: "unlimited" }
  - { domain: "{{ common_system_domain }}", type: '-', limit_item: 'locks', value: "unlimited" }
  - { domain: "{{ common_system_domain }}", type: '-', limit_item: 'as', value: "unlimited" }

common_sysctl_roles_tuning_overrides:
# Maximum open file descriptors
  - name: fs.file-max
    value: "1000000"
# Maximum network device backlog
  - name: net.core.netdev_max_backlog
    value: "16384"
# Maximum socket receive buffer
  - name: net.core.optmem_max
    value: "65535"
# Socket receive buffer
  - name: net.ipv4.tcp_rmem
    value: "8192 1048576 16777216"
# Maximum backlog of pending connections
  - name: net.core.somaxconn
    value: "65535"
# Enable TCP ECN
  - name: net.ipv4.tcp_ecn
    value: "1"
# Socket send buffer
  - name: net.ipv4.tcp_wmem
    value: "8192 1048576 16777216"
# Minimum amount of data in the send buffer before TCP starts sending
  - name: net.ipv4.tcp_notsent_lowat
    value: "16384"
# Enable IP forwarding
  - name: net.ipv4.ip_forward
    value: "1"
# Enable TCP Fast Open
  - name: net.ipv4.tcp_fastopen
    value: "3"
# TCP FIN timeout period
  - name: net.ipv4.tcp_fin_timeout
    value: "25"
# Maximum orphaned TCP sockets
  - name: net.ipv4.tcp_max_orphans
    value: "819200"
# Maximum TCP SYN backlog
  - name: net.ipv4.tcp_max_syn_backlog
    value: "20480"
# Maximum TCP Time Wait buckets
  - name: net.ipv4.tcp_max_tw_buckets
    value: "1440000"
# TCP memory limits
  - name: net.ipv4.tcp_mem
    value: "65536 131072 262144"
# Enable TCP MTU probing
  - name: net.ipv4.tcp_mtu_probing
    value: "1"
# Retries for TCP socket to establish connection
  - name: net.ipv4.tcp_retries2
    value: "8"
# Disable TCP slow start after idle
  - name: net.ipv4.tcp_slow_start_after_idle
    value: "0"
# Enable TCP window scaling
  - name: net.ipv4.tcp_window_scaling
    value: "1"
# UDP memory limits
  - name: net.ipv4.udp_mem
    value: "65536 131072 262144"
# Maximum queue length of UNIX domain sockets
  - name: net.unix.max_dgram_qlen
    value: "50"
# Minimum free Kbytes at which VM pressure happens
  - name: vm.min_free_kbytes
    value: "65536"
# How aggressively swap memory pages are used
  - name: vm.swappiness
    value: "10"
# Controls the tendency of the kernel to reclaim the memory which is used for caching of directory and inode objects.
  - name: vm.vfs_cache_pressure
    value: "50"
  # Default queuing discipline for network devices
  - name: net.core.default_qdisc
    value: "fq"
  # TCP congestion control algorithm
  - name: net.ipv4.tcp_congestion_control
    value: "bbr"

# CPU levels
common_levels:
  - { level: 1, features: 'lm|cmov|cx8|fpu|fxsr|mmx|syscall|sse2' }
  - { level: 2, features: 'cx16|lahf|popcnt|sse4_1|sse4_2|ssse3' }
  - { level: 3, features: 'avx|avx2|bmi1|bmi2|f16c|fma|abm|movbe|xsave' }
  - { level: 4, features: 'avx512f|avx512bw|avx512cd|avx512dq|avx512vl' }

# xanmod repo configuration
common_xanmod_apt_gpg_key: "https://dl.xanmod.org/archive.key"
common_xanmod_apt_ansible_distribution: "{{ ansible_distribution }}"
common_xanmod_apt_filename: "xanmod-kernel"
common_xanmod_gpt_key_path: "/etc/apt/trusted.gpg"
common_xanmod_repo_url: "http://deb.xanmod.org"
common_xanmod_apt_release_channel: "main"
common_xanmod_apt_repository: "deb [signed-by={{ common_xanmod_gpt_key_path }}] {{ common_xanmod_repo_url }} releases {{ common_xanmod_apt_release_channel }}"

common_xanmod_package_name: "linux-xanmod-x64v{{ current_level }}"

# Default for firewall
common_open_ports: ""
