---

marzban_system_dirs:
  - base_dir: "/opt/marzban"
  - vault_dir: "/opt/marzban/credentials"
  - work_dir: "/var/lib/marzban"
  - certs_dir: "/var/lib/marzban/certs"
  - templates_dir: "/var/lib/marzban/templates"

marzban_node_dirs:
  - base_dir: "/opt/marzban"
  - work_dir: "/var/lib/marzban-node"

marzban_ssl_certfile: "{{ vault_ssl_certs.keys() | select('search', 'cert') | list | first }}"
marzban_ssl_keyfile: "{{ vault_ssl_certs.keys() | select('search', 'key') | list | first }}"
marzban_ssl_ca_type: "public"

marzban_image: "gozargah/marzban"
marzban_image_tag: "latest"

marzban_haproxy_image: "haproxy"
marzban_haproxy_image_tag: "2.4.28"
marzban_haproxy_dirs:
  - etc_dir: "/etc/haproxy"


### Panel configuration

marzban_panel_login: "admin"
marzban_panel_password: "verystrongpass"
marzban_custom_subscription_template: false

### XRAY configuration
marzban_domain: "example.com"
marzban_panel_uri: "{{ marzban_domain }}"

marzban_vless_inbound_tag: "VLESS TCP REALITY"

marzban_vless_tcp_reality_port: "12000"
marzban_panel_port: "10000"

marzban_api_ports:
  - "62050"
  - "62051"

marzban_sni: "discordapp.com"

# If null role generate X25519 automatically at marzban_vless_private_key_path
marzban_vless_private_key: ""
marzban_vless_private_key_path: "{{ marzban_system_dirs | json_query('[*].vault_dir') | first }}/x25519_key"

marzban_vless_shortids: ""

marzban_dns_servers:
  - "8.8.8.8"

marzban_direct_domains:
  - "full:cp.cloudflare.com"
  - "domain:msftconnecttest.com"
  - "domain:msftncsi.com"
  - "domain:connectivitycheck.gstatic.com"
  - "domain:captive.apple.com"
  - "full:detectportal.firefox.com"
  - "domain:networkcheck.kde.org"

### Host info configuration

marzban_panel_host_info:
  - remark: "VLESS-PANEL"
    address: "{{ marzban_domain }}"
    port: 443


### WARP configuration
marzban_warp: false

marzban_warp_domains:
  - "geosite:openai"
  - "domain:ipinfo.io"
  - "iplocation.net"
  - "domain:spotify.com"
  - "domain:linkedin.com"

### Swagger and docs /docs and /redoc
marzban_docs: false

### Mysql(mariadb) configuration

marzban_mysql_instance: false
marzban_mysql_image: "mariadb"
marzban_mysql_image_tag: "lts"
marzban_mysql_db_name: "marzban"
marzban_mysql_user_name: "marzban"
marzban_mysql_user_password: ""
marzban_mysql_root_password: ""

# tuning
marzban_mysql_innodb_open_files: "1024"
marzban_mysql_innodb_buffer_pool_size: ""
marzban_mysql_binlog_expire_logs_seconds: "5184000" # 60 days

### Backup
marzban_backup: false
marzban_backup_telegram_bot_token: ""
marzban_backup_telegram_chat_id: ""
marzban_backup_cron: { minute: "0", hour: "2", day: "*", month: "*", weekday: "*" }

### Node configuration

marzban_ssl_node_path: "/var/lib/marzban-node/ssl_client_cert.pem"
marzban_ssl_node_certificate: ""
marzban_nodes_host_info: ""

marzban_node_image: "gozargah/marzban-node"
marzban_node_image_tag: "latest"
