---
name: linter code
'on':
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: 'v-kamerdinerov.marzban-haproxy-ansible'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'v-kamerdinerov.marzban-haproxy-ansible'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Upgrade pip3.
        run: pip3 install --upgrade pip

      - name: Install test dependencies.
        run: pip3 install yamllint ansible-lint ansible jmespath

      - name: Lint code with yamllint.
        run: yamllint --format github .

      - name: Lint code with ansible-lint.
        run: ansible-lint -c .ansible-lint.yml --force-color -v